name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.5 [CE|EE|ECE 2.4.0-2.4.7] 25 Apr 2024
          tag_name: 1.0.5
          body: |-
            ### softcommerce/module-plenty-dampfi [1.0.5]
            - **Compatibility**: Compatibility with PHP 8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
